/*
    * This tells TypeScript that any .hbs file exports a string (the compiled template).
    *If your webpack configuration uses handlebars-loader, the actual import will work at runtime.
    * This file is auto-generated by the TypeScript compiler when it encounters an import of a .hbs file.
    * It provides a module declaration for .hbs files, allowing TypeScript to understand that when you import a .hbs file, it will be treated as a string.
    * The content of the .hbs file will be available as a string when imported.     
    * For example, if you have a file named 'emailTemplate.hbs', you can import it in your TypeScript code like this:
    * 
    * import emailTemplate from './emailTemplate.hbs';
    * 
    * The 'emailTemplate' variable will then contain the content of the 'emailTemplate.hbs' file as a string.
*/

declare module '*.hbs' {
  const content: (data: any) => string;
  export default content;
}